using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace IndividualProjectFinalPartA_Danieel_Bogdan
{   
    class PrivateSchool
    {
        // Data Base Connection
        static string connectionString =
            @"Server = LAPTOP-KQG7KTD0\SQLEXPRESS; Database = IndividiualProject_PartB_DanieelBogdan; Trusted_Connection = True;";

        static SqlConnection sqlConnection = new SqlConnection(connectionString);

        // Start of Private School Class
        private const int MinimumFees = 100;
        private const int MaximumFees = 2500;
        private const int MinCharactersAllowed = 2;

        public List<Student> PRS_Students { get; set; }
        public List<Course> PRS_Courses { get; set; }
        public List<Assignment> PRS_Assignments { get; set; }
        public List<Trainer> PRS_Trainers { get; set; }

        public PrivateSchool()
        {
            PRS_Students = new List<Student>();
            PRS_Courses = new List<Course>();
            PRS_Assignments = new List<Assignment>();
            PRS_Trainers = new List<Trainer>();
        }

        public static Trainer GetTrainer()
        {
            // Values used in other actions
            bool activated = true;
            string choice = "";
            List<Trainer> trainers = new List<Trainer>();

            //Values Needed to create Trainer
            string firstName = "";
            string lastName = "";
            string subject = "";

            // Process to give the user the ability to chose if he wants to automate the generation
            Console.WriteLine("Use Synthetic Data? Y/N");
            choice = Console.ReadLine();
            switch (choice.ToUpper())
            {
                case "Y":                    
                    do
                    {
                        try
                        {
                            var trainer1 = new Trainer(firstName, lastName, subject);
                            trainers.Add(trainer1);                            
                            
                            activated = false;

                        }
                        catch (CustomException ex)
                        {
                            Console.WriteLine(ex.Message);
                            activated = true;
                        }

                    } while (activated);                    
                                                    
                    Console.WriteLine("Trainer Succesfully created.");                    
                    return trainers[0];

                case "N":
                    do
                    {
                        do
                        {
                            // Trainer First Name Creation
                            try
                            {
                                Console.WriteLine("Please Write The Trainer First Name");
                                firstName = Console.ReadLine();                               

                                if (firstName.Length == 0)
                                    Console.WriteLine("The trainers first Name will be autogenerated later.");
                                else if (firstName.Length < MinCharactersAllowed)
                                {
                                    throw new CustomException($"First name must be more than 4 characters");
                                }
                                if (!firstName.All(Char.IsLetterOrDigit))
                                {
                                    throw new CustomException($"First Name should contain only Alphanumerical Characters");
                                }

                                activated = false;
                            }
                            catch (CustomException ex)
                            {
                                activated = true;
                                Console.WriteLine(ex.Message);
                            }
                        } while (activated);

                        // Trainer Last Name Creation
                        do
                        {
                            try
                            {
                                Console.WriteLine("Please Write The Trainer Last Name");
                                lastName = Console.ReadLine();
                                
                                if (lastName.Length == 0)
                                    Console.WriteLine("The trainers last Name will be autogenerated later.");
                                else if (lastName.Length < MinCharactersAllowed)
                                {
                                    throw new CustomException($"Last name must be more than 4 characters");
                                }
                                if (!lastName.All(Char.IsLetterOrDigit))
                                {
                                    throw new CustomException($"Last Name should contain only Alphanumerical Characters");
                                }

                                activated = false;
                            }
                            catch (CustomException ex)
                            {
                                activated = true;
                                Console.WriteLine(ex.Message);
                            }
                        } while (activated);

                        // Trainer Subject Creation
                        do
                        {
                            try
                            {
                                Console.WriteLine("Please Write The Subject the Trainer is Specialized on");
                                subject = Console.ReadLine();                                

                                if (subject.Length == 0)
                                    Console.WriteLine("The trainers first subject will be autogenerated later.");
                            }
                            catch (CustomException ex)
                            {
                                activated = true;
                                Console.WriteLine(ex.Message);
                            }

                            activated = false;

                        } while (activated);

                        // Trainer Creation
                        try
                        {
                            var trainer1 = new Trainer(firstName, lastName, subject);
                            trainers.Add(trainer1);                           

                            activated = false;

                        }
                        catch (CustomException ex)
                        {
                            Console.WriteLine(ex.Message);
                            activated = true;
                        }                      
                       
                    } while (activated);

                    Console.WriteLine("Trainer Succesfully created.");
                    return trainers[0];

                default:
                    Console.WriteLine("Something was wrong. Generation will start Again");
                    return PrivateSchool.GetTrainer();
            }
        }

        public static Course GetCourse()
        {
            // Values need to Create a Course
            string cTitle = "";
            string cStream = "";
            string cType = "";
            string choice = "";
            List<Course> courses = new List<Course>();

            // Values used for the loop
            bool activated = true;

            // Values to use in Dates            
            int startYear = 0;
            int startMonth = 0;
            int startDay = 0;
            int endYear = 0;
            int endMonth = 0;
            int endDay = 0;

            // Process to give the user the ability to chose if he wants to automate the generation
            Console.WriteLine("Use Synthetic Data? Y/N");
            choice = Console.ReadLine();
            switch (choice.ToUpper())
            {
                case "Y":                    
                    do
                    {
                        try
                        {                            
                            courses.Add(new Course(cTitle, cStream, cType, startYear, startMonth, startDay, endYear, endMonth, endDay));

                            activated = false;
                        }
                        catch (CustomException ex)
                        {
                            activated = true;
                            Console.WriteLine(ex.Message);
                        }

                    } while (activated);

                    // Returning the courses that we have created and put in the list to be able to get out of the loop
                    Console.WriteLine("Course Succesfully created.");
                    return courses[0];                  

                // User will input the Data for the Course
                // There are Checks made in case of wrong Inputs
                case "N":
                    do
                    {
                        // Course Title Creation
                        do
                        {
                            try
                            {
                                Console.WriteLine("Please Write The Course Title");
                                cTitle = Console.ReadLine();
                                if (cTitle.Length == 0)
                                    Console.WriteLine("The course Title will be autogenerated later");
                                else if (cTitle.Length < MinCharactersAllowed)
                                {
                                    throw new CustomException($"Course Title must be more than {MinCharactersAllowed} characters");
                                }
                                activated = false;
                            }
                            catch (CustomException ex)
                            {
                                activated = true;
                                Console.WriteLine(ex.Message);
                            }

                        } while (activated);                            

                        // Course Stream Creation
                        do
                        {
                            try
                            {
                                Console.WriteLine("Please Write The Course Stream");
                                cStream = Console.ReadLine();
                                if (cStream.Length == 0)
                                    Console.WriteLine("The course Stream will be autogenerated later");
                                else if(cStream.Length < MinCharactersAllowed)
                                {
                                    throw new CustomException($"Course Stream must be more than {MinCharactersAllowed} characters");
                                }

                                activated = false;
                            }
                            catch (CustomException ex)
                            {
                                activated = true;
                                Console.WriteLine(ex.Message);
                            }

                        } while (activated);                            

                        // Course Type Creation
                        do
                        {
                            try
                            {
                                Console.WriteLine("Please Write The Course Type");
                                cType = Console.ReadLine();
                                if (cType.Length == 0)
                                    Console.WriteLine("The course Type will be autogenerated later");

                                activated = false;
                            }
                            catch (CustomException ex)
                            {
                                activated = true;
                                Console.WriteLine(ex.Message);
                            }

                        } while (activated);       
                       
                        // Course Starting date Creation
                        do
                        {
                            try
                            {
                                Console.WriteLine("Please Write the Year that the Course will Start");
                                string checkYear = Console.ReadLine();
                                if (checkYear.Length == 0)
                                {
                                    startYear = 0;
                                    Console.WriteLine("The course starting Year will be autogenerated later");
                                }
                                else if (startYear < 2018 || startYear > 2021)
                                {
                                    throw new CustomException($"Please for a Starting date enter a value between 2018 and 2021");
                                }
                                else
                                {
                                    startYear = int.Parse(checkYear);
                                }

                                activated = false;

                            }
                            catch (CustomException ex)
                            {
                                activated = true;
                                Console.WriteLine(ex.Message);
                            }                           
                        } while (activated);

                        // Course Starting month Creation
                        do
                        {
                            try
                            {
                                Console.WriteLine("Please Write the Month that the Course will Start");
                                string checkMonth = Console.ReadLine();
                                if (checkMonth.Length == 0)
                                {
                                    startMonth = 0;
                                    Console.WriteLine("The course starting Month will be autogenerated later");
                                }
                                else if (startMonth < 1 || startMonth > 12)
                                {
                                    throw new CustomException($"Please enter a value between 1 and 12");
                                }
                                else
                                {
                                    startMonth = int.Parse(checkMonth);
                                }

                                activated = false;

                            }
                            catch (CustomException ex)
                            {
                                activated = true;
                                Console.WriteLine(ex.Message);
                            }

                        } while (activated);

                        // Course Starting day Creation
                        do
                        {
                            try
                            {
                                Console.WriteLine("Please Write the Day that the Course will Start");
                                string checkDay = Console.ReadLine();
                                if (checkDay.Length == 0)
                                {
                                    startDay = 0;
                                    Console.WriteLine("The course starting Day will be autogenerated later");
                                }
                                else if (startDay < 1 || startDay > 30)
                                {
                                    throw new CustomException($"Please enter a value between 1 and 30");
                                }
                                else
                                {
                                    startDay = int.Parse(checkDay);
                                }

                                activated = false;
                            }
                            catch (CustomException ex)
                            {
                                activated = true;
                                Console.WriteLine(ex.Message);
                            }

                        } while (activated);

                        // Course Ending date Creation
                        do
                        {
                            try
                            {
                                Console.WriteLine("Please Write the Year that the Course will End");
                                string checkYear = Console.ReadLine();
                                if (checkYear.Length == 0)
                                {
                                    endYear = 0;
                                    Console.WriteLine("The course Ending Year will be autogenerated later");
                                }
                                else if (endYear < 2018 || endYear > 2022)
                                {
                                    throw new CustomException($"Please for a Starting date enter a value between 2018 and 2022");
                                }
                                else
                                {
                                    endYear = int.Parse(checkYear);
                                }

                                activated = false;
                            }
                            catch (CustomException ex)
                            {
                                activated = true;
                                Console.WriteLine(ex.Message);
                            }

                        } while (activated);

                        // Course Ending Month Creation
                        do
                        {
                            try
                            {
                                Console.WriteLine("Please Write the Month that the Course will End");
                                string checkMonth = Console.ReadLine();
                                if (checkMonth.Length == 0)
                                {
                                    endMonth = 0;
                                    Console.WriteLine("The course ending Month will be autogenerated later");
                                }
                                else if (endMonth < 1 || endMonth > 12)
                                {
                                    throw new CustomException($"Please enter a value between 1 and 12");
                                }
                                else
                                {
                                    endMonth = int.Parse(checkMonth);
                                }

                                activated = false;
                            }
                            catch (CustomException ex)
                            {
                                activated = true;
                                Console.WriteLine(ex.Message);
                            }

                        } while (activated);

                        // Course Ending Day Creation
                        do
                        {
                            try
                            {
                                Console.WriteLine("Please Write the Day that the Course will End");
                                string checkDay = Console.ReadLine();
                                if (checkDay.Length == 0)
                                {
                                    endDay = 0;
                                    Console.WriteLine("The course ending Day will be autogenerated later");
                                }
                                else if (endDay < 1 || endDay > 30)
                                {
                                    throw new CustomException($"Please enter a value between 1 and 30");
                                }
                                else
                                {
                                    endDay = int.Parse(checkDay);
                                }

                                activated = false;
                            }
                            catch (CustomException ex)
                            {
                                activated = true;
                                Console.WriteLine(ex.Message);
                            }

                        } while (activated);                        

                        // Ensuring the data is correct for creating a course
                        try
                        {
                            courses.Add(new Course(cTitle, cStream, cType, startYear, startMonth, startDay, endYear, endMonth, endDay));
                            activated = false;
                        }
                        catch (CustomException ex)
                        {
                            activated = true;
                            Console.WriteLine(ex.Message);
                        }

                    } while (activated);
                    
                    // Returning the courses that we have created and put in the list to be able to get out of the loop
                    Console.WriteLine("Course Succesfully Created");
                    return courses[0];

                default:
                    Console.WriteLine("Error. Please choose Yes/No");
                    return PrivateSchool.GetCourse();
            }
        }

        public static Student GetStudent()
        {
            // Values that the Student creation needs
            string sFirstName = "";
            string sLastName = "";
            double sFees = 0;
            string choice = "";
            List<Student> students = new List<Student>();

            // Values for checks and random Generation
            Random random = new Random();
            bool activated = true;            

            // Values to use in Dates                    
            int sYearofBirth = 0;
            int sMonthOfBirth = 0;
            int sDayOfBirth = 0;

            //Process to give the user the ability to chose if he wants to automate the generation
            Console.WriteLine("Use Synthetic Data? Y/N");
            choice = Console.ReadLine();
            switch (choice.ToUpper())
            {
                // User will input the Data for the Student
                // There are No wrong input Generations
                case "Y":                    
                    do
                    {
                        try
                        {
                            students.Add(new Student(sFirstName, sLastName, sYearofBirth, sMonthOfBirth, sDayOfBirth, sFees));
                            activated = false;

                        }
                        catch (CustomException ex)
                        {
                            activated = true;
                            Console.WriteLine(ex.Message);
                        }
                    } while (activated);                                      

                    // I create the last student here, ensuring that he is created with the same detail that student 3 is created. All checks are passed. I could just add them to list, but ok....                                     
                    Console.WriteLine("Student Succesfully created.");
                    return students[0];

                // User will input the Data for the Student
                // There are Checks made in case of wrong Inputs
                case "N":
                    do
                    {
                        // Student First Name Creation
                        do
                        {
                            try
                            {
                                Console.WriteLine("Please Write The Student First Name");
                                sFirstName = Console.ReadLine();
                                if (sFirstName.Length == 0)
                                    Console.WriteLine("The students first name will be auto generated later");
                                else if (sFirstName.Length < MinCharactersAllowed)
                                {
                                    throw new CustomException($"First name must be more than 4 characters");
                                }
                                if (!sFirstName.All(Char.IsLetterOrDigit))
                                {
                                    throw new CustomException($"First Name should contain only Alphanumerical Characters");
                                }

                                activated = false;
                            }
                            catch (CustomException ex)
                            {
                                activated = true;
                                Console.WriteLine(ex.Message);
                            }

                        } while (activated);

                        // Student Last Name Creation
                        do
                        {
                            try
                            {
                                Console.WriteLine("Please Write The Student Last Name");
                                sLastName = Console.ReadLine();
                                if (sLastName.Length == 0)
                                    Console.WriteLine("The students last name will be auto generated later");
                                else if (sLastName.Length < MinCharactersAllowed)
                                {
                                    throw new CustomException($"Last name must be more than 4 characters");
                                }

                                if (!sLastName.All(Char.IsLetterOrDigit))
                                {
                                    throw new CustomException($"Last Name should contain only Alphanumerical Characters");
                                }

                                activated = false;
                            }
                            catch (CustomException ex)
                            {
                                activated = true;
                                Console.WriteLine(ex.Message);
                            }

                        } while (activated);
                        
                        // Student Birth Date Creation
                        // Year of Student Birth
                        do
                        {
                            try
                            {
                                Console.WriteLine("Please Write The Student Year of Birth");
                                string checkYear = Console.ReadLine();
                                if (checkYear.Length == 0)
                                {
                                    sYearofBirth = 0;
                                    Console.WriteLine("The course starting Year will be autogenerated later");
                                }
                                else if (sYearofBirth > 2004 || sYearofBirth < 1970)
                                {
                                    throw new CustomException($"You must enter a year value bigger 1970 and smaller than 2004");
                                }
                                else
                                {
                                    sYearofBirth = int.Parse(checkYear);
                                }

                                activated = false;
                            }
                            catch (CustomException ex)
                            {
                                activated = true;
                                Console.WriteLine(ex.Message);
                            }

                        } while (activated);

                        // Month of Student Birth
                        do
                        {
                            try
                            {
                                Console.WriteLine("Please Write The Student Month of Birth");
                                string checkMonth = Console.ReadLine();
                                if (checkMonth.Length == 0)
                                {
                                    sMonthOfBirth = 0;
                                    Console.WriteLine("The student month of Birth will be autogenerated later");
                                }
                                else if (sMonthOfBirth < 1 || sMonthOfBirth > 12)
                                {
                                    throw new CustomException("In our Solar system there are 12 months. Please enter a value between 1 and 12");
                                }
                                else
                                {
                                    sMonthOfBirth = int.Parse(checkMonth);
                                }

                                activated = false;
                            }
                            catch (CustomException ex)
                            {
                                activated = true;
                                Console.WriteLine(ex.Message);
                            }

                        } while (activated);

                        // Day of Student Birth
                        do
                        {
                            try
                            {
                                Console.WriteLine("Please Write The Student Day of Birth");
                                string checkDay = Console.ReadLine();
                                if (checkDay.Length == 0)
                                {
                                    sDayOfBirth = 0;
                                    Console.WriteLine("The student day of Birth will be autogenerated later");
                                }
                                else if (sDayOfBirth < 1 || sDayOfBirth > 30)
                                {
                                    throw new CustomException("Please pick a day between 1 and 30");
                                }
                                else
                                {
                                    sDayOfBirth = int.Parse(checkDay);
                                }

                                activated = false;
                            }
                            catch (CustomException ex)
                            {
                                activated = true;
                                Console.WriteLine(ex.Message);
                            }

                        } while (activated);

                        // Student Fees Creation
                        do
                        {
                            try
                            {
                                Console.WriteLine("Please Write how much the student will be paying for the Course");
                                string checkFees = Console.ReadLine();
                                if (checkFees.Length == 0)
                                {
                                    sFees = 0;
                                    Console.WriteLine("The student fees will be autogenerated later");
                                }
                                else if (sFees <= MinimumFees || sFees >= MaximumFees)
                                {
                                    throw new CustomException(sFees <= MinimumFees ? $"Fees cannot be smaller than {MinimumFees}" : $"Fees cannot be bigger than {MaximumFees}");
                                }
                                else
                                {
                                    sFees = int.Parse(checkFees);
                                }

                                activated = false;
                            }
                            catch (CustomException ex)
                            {
                                activated = true;
                                Console.WriteLine(ex.Message);
                            }

                        } while (activated);                     

                        // Ensuring the data is correct for creating a student
                        try
                        {
                            // Generating the student
                            students.Add(new Student(sFirstName, sLastName, sYearofBirth, sMonthOfBirth, sDayOfBirth, sFees));
                            activated = false;                                                       
                        }
                        catch (CustomException ex)
                        {
                            activated = true;
                            Console.WriteLine(ex.Message);
                        }

                    } while (activated);

                    Console.WriteLine("Student Succesfully created.");
                    return students[0];

                default:
                    Console.WriteLine("ERROR. THE GENERATION WILL START AGAIN");
                    return PrivateSchool.GetStudent();
            }
        }

        public static Assignment GetAssignment()
        {
            // Values used in Assignments Creation
            string aTitle = "";
            string aDescreption = "";         
            string choice = "";
            List<Assignment> assignments = new List<Assignment>();

            // Values for checks and random Generation
            Random random = new Random();
            bool activated = true;

            // Values to use in Dates            
            int aSubYearDate = 0;
            int aSubMonthDate = 0;
            int aSubDayDate = 0;

            // Process to give the user the ability to chose if he wants to automate the generation
            Console.WriteLine("Use Synthetic Data? Y/N");
            choice = Console.ReadLine();
            switch (choice.ToUpper())
            {
                case "Y":
                    do
                    {
                        try
                        {
                            assignments.Add(new Assignment(aTitle, aDescreption, aSubYearDate, aSubMonthDate, aSubDayDate));
                            activated = false;
                        }
                        catch (CustomException ex)
                        {
                            activated = true;
                            Console.WriteLine(ex.Message);
                        }

                    } while (activated);

                    // I create an assignment here identical to assignment 1, ensureing assignment2 wont crush because assignment1 passed all the checks. Could do it with lists but ok....                                        
                    Console.WriteLine("Assignment Succesfully created");
                    return assignments[0];


                // User will input the Data for the Assignment
                // There are Checks made in case of wrong Inputs
                case "N":
                    do
                    {
                        // Assignment Title Creation
                        do
                        {
                            try
                            {
                                Console.WriteLine("Please Write The Assignment Title");
                                aTitle = Console.ReadLine();
                                if (aTitle.Length == 0)
                                    Console.WriteLine("Assignment title will be auto generated later");
                                else if (aDescreption.Length <= MinCharactersAllowed)
                                {
                                    throw new CustomException($"Assignment Descreption must be more than 2 characters");
                                }

                                activated = false;
                            }
                            catch (CustomException ex)
                            {
                                activated = true;
                                Console.WriteLine(ex.Message);
                            }

                        } while (activated);

                        // Assignment Descreption Creation
                        do
                        {
                            try
                            {
                                Console.WriteLine("Please Write The Assignment Descreption");
                                aDescreption = Console.ReadLine();
                                if (aDescreption.Length == 0)
                                    Console.WriteLine("Assignment descreption will be auto generated later");
                                else if (aDescreption.Length <= MinCharactersAllowed)
                                {
                                    throw new CustomException($"Assignment Descreption must be more than 2 characters");
                                }

                                activated = false;
                            }
                            catch (CustomException ex)
                            {
                                activated = true;
                                Console.WriteLine(ex.Message);
                            }

                        } while (activated);


                        // Assignment sub date Creation
                        // Year of Assignment sub Date
                        do
                        {
                            try
                            {
                                Console.WriteLine("Please Write the year that the assingment must be subbed");
                                string checkYear = Console.ReadLine();
                                if (checkYear.Length == 0)
                                {
                                    aSubYearDate = 0;
                                    Console.WriteLine("The year that the assingment must be subbed will be autogenerated later");
                                }
                                else if (aSubYearDate < 2018 || aSubYearDate > 2022)
                                {
                                    throw new CustomException("Please enter a Year between 2018 and 2020");

                                }
                                else
                                {
                                    aSubYearDate = int.Parse(checkYear);
                                }

                                activated = false;
                            }
                            catch (CustomException ex)
                            {
                                activated = true;
                                Console.WriteLine(ex.Message);
                            }

                        } while (activated);

                        // Month of Assignment sub
                        do
                        {
                            try
                            {
                                Console.WriteLine("Please Write the Month that the assingment must be subbed");
                                string checkMonth = Console.ReadLine();
                                if (checkMonth.Length == 0)
                                {
                                    aSubMonthDate = 0;
                                    Console.WriteLine("The Month that the assingment must be subbed will be autogenerated later");
                                }
                                else if (aSubMonthDate < 1 || aSubMonthDate > 12)
                                {
                                    throw new CustomException($"In our Solar system there are 12 months. Please enter a value between 1 and 12");
                                }
                                else
                                {
                                    aSubMonthDate = int.Parse(checkMonth);
                                }

                                activated = false;
                            }
                            catch (CustomException ex)
                            {
                                activated = true;
                                Console.WriteLine(ex.Message);
                            }

                        } while (activated);

                        // Day of Assignment sub
                        do
                        {
                            try
                            {
                                Console.WriteLine("Please Write the Day that the assingment must be subbed");
                                string checkDay = Console.ReadLine();
                                if (checkDay.Length == 0)
                                {
                                    aSubDayDate = 0;
                                    Console.WriteLine("The Day that the assingment must be subbed will be autogenerated later");
                                }
                                else if (aSubDayDate < 1 || aSubDayDate > 30)
                                {
                                    throw new CustomException($"Please enter a value between 1 and 30");
                                }
                                else
                                {
                                    aSubDayDate = int.Parse(checkDay);
                                }

                                activated = false;
                                
                            }
                            catch (CustomException ex)
                            {
                                activated = true;
                                Console.WriteLine(ex.Message);
                            }

                        } while (activated);                      
                            
                        // Ensuring the data is correct for creating an Assignment
                        try
                        {
                            // Assignment Creation
                            assignments.Add(new Assignment(aTitle, aDescreption, aSubYearDate, aSubMonthDate, aSubDayDate));
                            activated = false;
                            
                        }
                        catch (CustomException ex)
                        {
                            activated = true;
                            Console.WriteLine(ex.Message); ;
                        }
                    } while (activated);

                    // Assignment Creation                                     
                    Console.WriteLine("Assignment Succesfully Created");
                    return assignments[0];

                default:
                    Console.WriteLine("ERROR. THE GENERATION WILL START AGAIN");
                    return PrivateSchool.GetAssignment();
            }
        }

        public static void AddStudentToCourseDATABASE()
        {           
            try
            {
                // Open Sql Conenction
                sqlConnection.Open();

                // Here we will see the student list so we can choose whom we want to Enroll to a Course 
                SqlCommand  cmdSelect = new SqlCommand("SELECT ID, S_FirstName, S_LastName FROM Student", sqlConnection);
                SqlDataReader DataReader = cmdSelect.ExecuteReader();
                Console.WriteLine("The below Students are enrolled to our Private School");

                while (DataReader.Read())
                {
                    Console.WriteLine($"Student ID: {DataReader.GetInt32(0)} Studnet Full Name: {DataReader.GetString(1)} {DataReader.GetString(2)}");
                }

                // Reader Must Close
                DataReader.Close();
                // Connection Must Close
                sqlConnection.Close();

                // Open Sql Conenction Again
                sqlConnection.Open();

                // Here we will see the Courses List so we can choose where we want to Enroll The students
                cmdSelect = new SqlCommand("SELECT ID, C_Title, C_Stream, C_Type FROM COURSE", sqlConnection);
                DataReader = cmdSelect.ExecuteReader();
                Console.WriteLine("The Courses in our Private School Are:");

                while (DataReader.Read())
                {
                    Console.WriteLine($"Course ID: {DataReader.GetInt32(0)} Course Title: {DataReader.GetString(1)}. The Course Stream is: {DataReader.GetString(2)}. It's {DataReader.GetString(3)}");
                }

                // Reader Must Close
                DataReader.Close();
                // Connection Must Close
                sqlConnection.Close();

                // Open Sql Conenction Again
                sqlConnection.Open();

                // Somewhere bellow i must write some checks, like not to be able to insert the same student in the same course twice.
                // Here the user will pick the IDs of the Instances so we can Combine them
                Console.WriteLine("Please pick student ID you want to enroll to a Course");
                int pickFirstInstanceID = int.Parse(Console.ReadLine());
                Console.WriteLine("Please pick the Course ID you want the Student to be enrolled");
                int pickSecondInstanceID = int.Parse(Console.ReadLine());

                // The querry to insert the Student to a Course will Run Here
                SqlCommand cmDInsert = new SqlCommand($"INSERT INTO StudentPerCourse(StudentID, CourseID) VALUES('{pickFirstInstanceID}', '{pickSecondInstanceID}')", sqlConnection);
                int rowsInserted = cmDInsert.ExecuteNonQuery();

                // Check if the insertion of the student was completed succesfully.
                if (rowsInserted > 0)
                {
                    Console.WriteLine("The Student was succesfully inserted in the Course");
                }
                else
                {
                    Console.WriteLine("Something went wrong with the insertion");
                }

                // Reader Must Close
                DataReader.Close();
                // Connection Must Close
                sqlConnection.Close();
            }
            catch (Exception ex)
            {                
                // Connection Must Close
                sqlConnection.Close();
                Console.WriteLine($"{ex.Message} Something went wrong with your DataBase");
            }

        }

        public static void AddTrainerToCourseDATABASE()
        {            
            try
            {
                // Open Sql Conenction
                sqlConnection.Open();

                // Here we will see the Trainer list so we can choose whom we want to Enroll to a Course 
                SqlCommand cmdSelect = new SqlCommand("SELECT ID, T_FirstName, T_LastName, T_Subject FROM Trainer", sqlConnection);
                SqlDataReader DataReader = cmdSelect.ExecuteReader();
                Console.WriteLine("The below Trainer are to teach in Our Private School");

                while (DataReader.Read())
                {
                    Console.WriteLine($"Trainer ID: {DataReader.GetInt32(0)} Trainer Full Name: {DataReader.GetString(1)} {DataReader.GetString(2)} and his Subject is: {DataReader.GetString(3)}");
                }

                // Reader Must Close
                DataReader.Close();
                // Connection Must Close
                sqlConnection.Close();

                // Open Sql Conenction Again
                sqlConnection.Open();

                // Here we will see the Courses List so we can choose where we want to Enroll The Trainer
                cmdSelect = new SqlCommand("SELECT ID, C_Title, C_Stream, C_Type FROM COURSE", sqlConnection);
                DataReader = cmdSelect.ExecuteReader();
                Console.WriteLine("The Courses in our Private School Are:");

                while (DataReader.Read())
                {
                    Console.WriteLine($"Course ID: {DataReader.GetInt32(0)} Course Title: {DataReader.GetString(1)}. The Course Stream is: {DataReader.GetString(2)}. It's {DataReader.GetString(3)}");
                }

                // Reader Must Close
                DataReader.Close();
                // Connection Must Close
                sqlConnection.Close();

                // Open Sql Conenction Again
                sqlConnection.Open();

                // Somewhere bellow i must write some checks, like not to be able to insert the same student in the same course twice.
                // Here the user will pick the IDs of the Instances so we can Combine them
                Console.WriteLine("Please pick Trainer ID you want to enroll to a Course");
                int pickFirstInstanceID = int.Parse(Console.ReadLine());
                Console.WriteLine("Please pick the Course ID you want the Trainer to be enrolled");
                int pickSecondInstanceID = int.Parse(Console.ReadLine());

                // The querry to insert the Trainer to a Course will Run Here
                SqlCommand cmDInsert = new SqlCommand($"INSERT INTO TrainerPerCourse(TrainerID, CourseID) VALUES('{pickFirstInstanceID}', '{pickSecondInstanceID}')", sqlConnection);
                int rowsInserted = cmDInsert.ExecuteNonQuery();

                // Check if the insertion of the student was completed succesfully.
                if (rowsInserted > 0)
                {
                    Console.WriteLine("The Trainer was succesfully inserted in the Course");
                }
                else
                {
                    Console.WriteLine("Something went wrong with the insertion");
                }

                // Reader Must Close
                DataReader.Close();
                // Connection Must Close
                sqlConnection.Close();
            }
            catch (Exception ex)
            {
                // Connection Must Close
                sqlConnection.Close();
                Console.WriteLine($"{ex.Message} Something went wrong with your DataBase");
            }
        }

        public static void AddAssignmentToCourseDATABASE()
        {
            try
            {
                // Open Sql Conenction
                sqlConnection.Open();

                // Here we will see the Trainer list so we can choose whom we want to Enroll to a Course 
                SqlCommand cmdSelect = new SqlCommand("SELECT ID, A_Title, A_Description FROM Assignment", sqlConnection);
                SqlDataReader DataReader = cmdSelect.ExecuteReader();
                Console.WriteLine("The below Assignments are Proposed:");

                while (DataReader.Read())
                {
                    Console.WriteLine($"Assignment ID: {DataReader.GetInt32(0)} Assignment Title: {DataReader.GetString(1)} where the Student must: {DataReader.GetString(2)}");
                }

                // Reader Must Close
                DataReader.Close();
                // Connection Must Close
                sqlConnection.Close();

                // Open Sql Conenction Again
                sqlConnection.Open();

                // Here we will see the Courses List so we can choose where we want to Enroll The Trainer
                cmdSelect = new SqlCommand("SELECT ID, C_Title, C_Stream, C_Type FROM COURSE", sqlConnection);
                DataReader = cmdSelect.ExecuteReader();
                Console.WriteLine("The Courses in our Private School Are:");

                while (DataReader.Read())
                {
                    Console.WriteLine($"Course ID: {DataReader.GetInt32(0)} Course Title: {DataReader.GetString(1)}. The Course Stream is: {DataReader.GetString(2)}. It's {DataReader.GetString(3)}");
                }

                // Reader Must Close
                DataReader.Close();
                // Connection Must Close
                sqlConnection.Close();

                // Open Sql Conenction Again
                sqlConnection.Open();

                // Somewhere bellow i must write some checks, like not to be able to insert the same student in the same course twice.
                // Here the user will pick the IDs of the Instances so we can Combine them
                Console.WriteLine("Please pick Assignment ID you want to enroll to a Course");
                int pickFirstInstanceID = int.Parse(Console.ReadLine());
                Console.WriteLine("Please pick the Course ID you want the Assignment to be enrolled");
                int pickSecondInstanceID = int.Parse(Console.ReadLine());

                // The querry to insert the Trainer to a Course will Run Here
                SqlCommand cmDInsert = new SqlCommand($"INSERT INTO AssignmentPerCourse(AssignmentID, CourseID) VALUES('{pickFirstInstanceID}', '{pickSecondInstanceID}')", sqlConnection);
                int rowsInserted = cmDInsert.ExecuteNonQuery();

                // Check if the insertion of the student was completed succesfully.
                if (rowsInserted > 0)
                {
                    Console.WriteLine("The Assignment was succesfully inserted in the Course");
                }
                else
                {
                    Console.WriteLine("Something went wrong with the insertion");
                }

                // Reader Must Close
                DataReader.Close();
                // Connection Must Close
                sqlConnection.Close();
            }
            catch (Exception ex)
            {
                // Connection Must Close
                sqlConnection.Close();
                Console.WriteLine($"{ex.Message} Something went wrong with your DataBase");
            }
        }

        public static void AddAssignmentToStudentDATABASE()
        {
            try
            {
                // Open Sql Conenction
                sqlConnection.Open();

                // Here we will see the Trainer list so we can choose whom we want to Enroll to a Course 
                SqlCommand cmdSelect = new SqlCommand("SELECT ID, A_Title, A_Description FROM Assignment", sqlConnection);
                SqlDataReader DataReader = cmdSelect.ExecuteReader();
                Console.WriteLine("The below Assignments are Proposed:");

                while (DataReader.Read())
                {
                    Console.WriteLine($"Assignment ID: {DataReader.GetInt32(0)} Assignment Title: {DataReader.GetString(1)} where the Student must: {DataReader.GetString(2)}");
                }

                // Reader Must Close
                DataReader.Close();
                // Connection Must Close
                sqlConnection.Close();

                // Open Sql Conenction Again
                sqlConnection.Open();

                // Here we will see the student list so we can choose whom we want to give an Assignment 
                cmdSelect = new SqlCommand("SELECT ID, S_FirstName, S_LastName FROM Student", sqlConnection);
                DataReader = cmdSelect.ExecuteReader();
                Console.WriteLine("The below Students are enrolled to our Private School");

                while (DataReader.Read())
                {
                    Console.WriteLine($"Student ID: {DataReader.GetInt32(0)} Studnet Full Name: {DataReader.GetString(1)} {DataReader.GetString(2)}");
                }

                // Reader Must Close
                DataReader.Close();
                // Connection Must Close
                sqlConnection.Close();

                // Open Sql Conenction Again
                sqlConnection.Open();

                // Somewhere bellow i must write some checks, like not to be able to insert the same student in the same course twice.
                // Here the user will pick the IDs of the Instances so we can Combine them
                Console.WriteLine("Please pick Assignment ID you want to give to a Student");
                int pickFirstInstanceID = int.Parse(Console.ReadLine());
                Console.WriteLine("Please pick the Student ID you want the Assignment to be given");
                int pickSecondInstanceID = int.Parse(Console.ReadLine());

                // The querry to give the Assignment to a student will Run Here
                SqlCommand cmDInsert = new SqlCommand($"INSERT INTO AssignmentPerStudent(AssignmentID, StudentID) VALUES('{pickFirstInstanceID}', '{pickSecondInstanceID}')", sqlConnection);
                int rowsInserted = cmDInsert.ExecuteNonQuery();

                // Check if the insertion of the student was completed succesfully.
                if (rowsInserted > 0)
                {
                    Console.WriteLine("The Assignment was succesfully given to the Student");
                }
                else
                {
                    Console.WriteLine("Something went wrong with the insertion");
                }

                // Reader Must Close
                DataReader.Close();
                // Connection Must Close
                sqlConnection.Close();
            }
            catch (Exception ex)
            {
                // Connection Must Close
                sqlConnection.Close();
                Console.WriteLine($"{ex.Message} Something went wrong with your DataBase");
            }
        }

        public static DateTime SubDateTime()
        {
            int subYear = 0;
            int subMonth = 0;
            int subDay = 0;
            string checkSubYear = "";
            string checkSubMonth = "";
            string checkSubDay = "";
            bool activated = true;
            Random random = new Random();

            do
            {
                try
                {
                    Console.WriteLine("Please write the year you want to check if there is an Assignments Subdue");
                    checkSubYear = Console.ReadLine();

                    if (checkSubYear.Length == 0)
                    {
                        Console.WriteLine("The year for Assignments Subdue will be autogenerated");
                        subYear = random.Next(2018, 2020);
                        Console.WriteLine($"Assignments Subdue year is: {subYear}");
                        activated = false;
                    }
                    else
                    {
                        subYear = int.Parse(checkSubYear);
                        activated = false;
                    }

                    if (subYear < 2018 || subYear > 2020)
                    {
                        throw new CustomException("The year for the assignment check should be between 2018 and 2020");
                    }
                }
                catch (CustomException ex)
                {
                    activated = true;
                    Console.WriteLine(ex.Message);
                }
            } while (activated);

            // Month of Assignment subdue
            do
            {
                try
                {
                    Console.WriteLine("Please write the month you want to check if there is an Assignments Subdue");
                    checkSubMonth = Console.ReadLine();

                    if (checkSubMonth.Length == 0)
                    {
                        Console.WriteLine("The month for Assignments Subdue will be auto generated");
                        subMonth = random.Next(1, 12);
                        Console.WriteLine($"The month for Assignments subdue is: {subMonth}");
                        activated = false;
                    }
                    else
                    {
                        subMonth = int.Parse(checkSubMonth);
                        activated = false;
                    }

                    if (subMonth < 1 || subMonth > 12)
                    {
                        throw new CustomException("The month for the assignment check should be between 1 and 12");
                    }
                }
                catch (CustomException ex)
                {
                    activated = true;
                    Console.WriteLine(ex.Message);
                }
            } while (activated);

            // Day of Assignment Sub
            do
            {
                try
                {
                    Console.WriteLine("Please write the day you want to check if there is an Assignments Subdue");
                    checkSubDay = Console.ReadLine();

                    if (checkSubDay.Length == 0)
                    {
                        Console.WriteLine("The day for Assignments Subdue will be auto enerated");
                        subDay = random.Next(1, 30);
                        Console.WriteLine($"Student Day of Birth is: {subDay}");
                        activated = false;
                    }
                    else
                    {
                        subDay = int.Parse(checkSubDay);
                        activated = false;
                        break;
                    }

                    if (subDay < 1 || subDay > 31)
                    {
                        throw new CustomException("The day for the assignment check should be between 1 and 31");
                    }
                }
                catch (CustomException ex)
                {
                    activated = true;
                    Console.WriteLine(ex.Message);
                }
            }
            while (activated);

            DateTime SubDateAssignment = new DateTime(subYear, subMonth, subDay);

            return SubDateAssignment;
        }

        // Add Instances to other Instances (Lists Needed in the Program - No DataBase Connection)
        //public static void AddStudentsToCourses(List<Course> courses, List<Student> students, int counter, int subCounter, int subCounter2, List<StudentPerCourse> listStudentPerCourse)
        //{
        //    // Pick the Student you want
        //    subCounter = 0;
        //    Console.WriteLine("................................................");
        //    Console.WriteLine("Please choose which Student you would like to Enroll to The Courses:");
        //    Console.WriteLine("");
        //    foreach (Student student in students)
        //    {
        //        subCounter++;
        //        Console.WriteLine($"Student number: {subCounter}: {student}");
        //    }
        //    subCounter2 = int.Parse(Console.ReadLine()) - 1;
        //    Console.WriteLine("Student succesfully picked.");

        //    // Pick the Course
        //    subCounter = 0;
        //    Console.WriteLine("................................................");
        //    Console.WriteLine("Please choose in which Course you would like to Enroll the students:");
        //    Console.WriteLine("");
        //    foreach (Course course in courses)
        //    {
        //        subCounter++;
        //        Console.WriteLine($"Course number: {subCounter}: {course}");
        //    }
        //    counter = int.Parse(Console.ReadLine()) - 1;
        //    var studentPerCourse = new StudentPerCourse(students[subCounter2], courses[counter]);

        //    // Add the course to the students Property of List of Courses.
        //    students[subCounter2].S_Courses.Add(courses[counter]);

        //    // Add Student per Course to a List to type it later
        //    listStudentPerCourse.Add(studentPerCourse);

        //    Console.WriteLine("Students succesfully enrolled to Courses");
        //}



        //public static void AddTrainersToCourses(List<Course> courses, List<Trainer> trainers, int counter, int subCounter, int subCounter2, List<TrainerPerCourse> listTrainerPerCourse)
        //{
        //    // Pick the Trainer
        //    subCounter = 0;
        //    Console.WriteLine("................................................");
        //    Console.WriteLine("Please choose which Trainer you would like to Enroll to The Courses:");
        //    Console.WriteLine("");
        //    foreach (Trainer trainer in trainers)
        //    {
        //        subCounter++;
        //        Console.WriteLine($"Trainer number: {subCounter}: {trainer}");
        //    }
        //    subCounter2 = int.Parse(Console.ReadLine()) - 1;
        //    Console.WriteLine("Trainer succesfully picked.");

        //    // Pick the Course
        //    subCounter = 0;
        //    Console.WriteLine("................................................");
        //    Console.WriteLine("Please choose in which Course you would like to Enroll the Trainers:");
        //    Console.WriteLine("");
        //    foreach (Course course in courses)
        //    {
        //        subCounter++;
        //        Console.WriteLine($"Course number: {subCounter}: {course}");
        //    }
        //    counter = int.Parse(Console.ReadLine()) - 1;
        //    var trainerPerCourse = new TrainerPerCourse(trainers[subCounter2], courses[counter]);
        //    // Add the course to the trainers Property of List of Courses.
        //    trainers[subCounter2].T_Courses.Add(courses[counter]);

        //    // Add Trainer per Course to a List to type it later
        //    listTrainerPerCourse.Add(trainerPerCourse);

        //    Console.WriteLine("Trainers succesfully enrolled to Courses");
        //}

        //public static void AddAssignmentsToCourse(List<Course> courses, List<Assignment> assignments, int counter, int subCounter, int subCounter2, List<AssignmentPerCourse> listAssignmentPerCourse)
        //{
        //    // Pick Assignment
        //    subCounter = 0;
        //    Console.WriteLine("................................................");
        //    Console.WriteLine("Please choose which Assignment you would like to Enroll to The Courses:");
        //    Console.WriteLine("");
        //    foreach (Assignment assignment in assignments)
        //    {
        //        subCounter++;
        //        Console.WriteLine($"Assignment number: {subCounter}: {assignment}");
        //    }
        //    subCounter2 = int.Parse(Console.ReadLine()) - 1;
        //    Console.WriteLine("Assignment succesfully picked.");

        //    // Pick Course
        //    subCounter = 0;
        //    Console.WriteLine("................................................");
        //    Console.WriteLine("Please choose in which Course you would like to Enroll the Assignments:");
        //    Console.WriteLine("");
        //    foreach (Course course in courses)
        //    {
        //        subCounter++;
        //        Console.WriteLine($"Course number {subCounter}: {course}");
        //    }
        //    counter = int.Parse(Console.ReadLine()) - 1;
        //    var assignmentPerCourse = new AssignmentPerCourse(assignments[subCounter2], courses[counter]);

        //    // Add the course to the Assignment Property of List of Courses.
        //    assignments[subCounter2].A_Courses.Add(courses[counter]);

        //    // Add Assignments per Course to a List to type it later
        //    listAssignmentPerCourse.Add(assignmentPerCourse);

        //    Console.WriteLine("Assignments succesfully enrolled to Courses");
        //}

        //public static void AddAssignmentsToStudent(List<Student> students, List<Assignment> assignments, int counter, int subCounter, int subCounter2, List<AssignmentPerStudent> listAssignmentPerStudent, List<MarkPerAssignmentPerStudent> listMarkPerAssignmentPerStudents)
        //{
        //    // Add Assignments to Students
        //    // Pick Assignment
        //    subCounter = 0;
        //    Console.WriteLine("................................................");
        //    Console.WriteLine("Please choose which Assignment you would like to Enroll to The Students:");
        //    Console.WriteLine("");
        //    foreach (Assignment assignment in assignments)
        //    {
        //        subCounter++;
        //        Console.WriteLine($"Assignment number: {subCounter}: {assignment}");
        //    }
        //    subCounter2 = int.Parse(Console.ReadLine()) - 1;
        //    Console.WriteLine("Assignment succesfully picked.");

        //    // Pick Student
        //    subCounter = 0;
        //    Console.WriteLine("................................................");
        //    Console.WriteLine("Please choose to which Students you would like to give the Assignments:");
        //    Console.WriteLine("");
        //    foreach (Student student in students)
        //    {
        //        subCounter++;
        //        Console.WriteLine($"Student number {subCounter}: {student}");
        //    }
        //    counter = int.Parse(Console.ReadLine()) - 1;
        //    var assignmentsPerStudent = new AssignmentPerStudent(assignments[subCounter2], students[counter]);

        //    // Add the assignment to the students Property of List of Assignments.
        //    students[counter].S_Assignments.Add(assignments[subCounter2]);

        //    // Add Assignments per Student to a List to type it later
        //    listAssignmentPerStudent.Add(assignmentsPerStudent);

        //    // Add Assignments and Students in a property in order to put them the oral and Total Mark Later
        //    MarkPerAssignmentPerStudent markPerAssignmentPerStudent = new MarkPerAssignmentPerStudent(students[counter], assignments[subCounter2], 0, 0);
        //    listMarkPerAssignmentPerStudents.Add(markPerAssignmentPerStudent);

        //    Console.WriteLine("Assignments succesfully enrolled to Students");
        //}


    }
}

